disabled_rules: # rule identifiers to exclude from running
- line_length
excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods
identifier_name:
  min_length: # only min_length
    error: 2 # only error
  excluded: # excluded via string array
    - id
    - url
    - map
